### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by feliperenan** [feliperenan/simple_form_bootstrap4#1]
- [ ] Check multiselect
- [ ] Check textarea
- [ ] form-inline
- [ ] Include form-check-label class on label when we have a collection of vertical_radio_and_checkboxes
- [ ] Add custom classes to inputs and labels generated by a input collection
- [ ] If the form is horizontal, all inputs should be to.
- [ ] horizontal_file_input
- [ ] multi_select
